name: Spell Check

on: [pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.7

      - name: apt installs
        run: sudo apt update && sudo apt install -y texlive-latex-extra texlive-lang-cyrillic ghostscript

      - uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.10'
      
      - name: pip installs
        run: pip install -r requirements.txt

      - name: Build English
        run: make html

      - name: Check for spelling errors
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: "_spelling/content/*.spelling"

      - name: Fail if spelling errors
        if: steps.check_files.outputs.files_exists == 'true'
        run: cat _spelling/content/* && exit 1
